class WorkSpaceSerializer < ActiveModel::Serializer
  attributes :id,
             :place_id,
             :lat,
             :lng,
             :name,
             :address,
             :photo,
             :phone,
             :user,
             :avg_rating,
             :avg_noise,
             :avg_wifi,
             :avg_bathroom,
             :avg_seating,
             :bool_alcohol,
             :bool_bathroom,
             :bool_coffee,
             :bool_food,
             :bool_goodforgroup,
             :bool_meetingspace,
             :bool_outdoorspace,
             :bool_outlet,
             :bool_parking,
             :bool_petfriendly,
             :bool_seating,
             :bool_wifi,
             :bool_wifipass,
             :votes_for,
             :reviews
  has_one :user
  has_many :reviews
end
