class WorkSpaceSerializer < ActiveModel::Serializer
  attributes :id,
             :place_id,
             :lat,
             :lng,
             :name,
             :address,
             :addresscomponent,
             :photo,
             :phone,
             :user,
             :avgclean,
             :avg_rating,
             :avgrating,
             :avg_noise,
             :avgnoise,
             :avg_wifi,
             :avgwifi,
             :avg_bathroom,
             :avgbathroom,
             :avg_seating,
             :avgseating,
             :bool_alcohol,
             :bool_bathroom,
             :bool_coffee,
             :bool_food,
             :bool_goodforgroup,
             :bool_meetingspace,
             :bool_outdoorspace,
             :bool_outlet,
             :bool_parking,
             :bool_petfriendly,
             :bool_seating,
             :bool_wifi,
             :bool_wifipass,
             :votes_for,
             :reviews,
             :update_bathroom,
             :update_noise,
             :update_rating,
             :update_seating,
             :update_wifi
  has_one :user
  has_many :reviews
end
